version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
      target: development
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/securevote_dev
      - JWT_SECRET=dev_secret
      - NETWORK_RPC_URL=http://hardhat:8545
    volumes:
      - ../apps/api:/app/apps/api
      - ../packages:/app/packages
    command: pnpm dev
    depends_on:
      - db
      - hardhat

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    volumes:
      - ../apps/web:/app/apps/web
      - ../packages:/app/packages
    command: pnpm dev
    depends_on:
      - api

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=securevote_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  hardhat:
    build:
      context: ..
      dockerfile: docker/Dockerfile.hardhat
    ports:
      - "8545:8545"
    environment:
      - NETWORK_ID=31337
    volumes:
      - ../apps/contracts:/app/apps/contracts

volumes:
  postgres_dev_data: