name: CI

on:
  # Disabled CI workflow - no automatic builds or tests
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch: # Only allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test API
        run: pnpm --filter api test --run

      - name: Test Contracts
        run: pnpm --filter contracts test

    # Web tests disabled - no test script available
    # - name: Test Web
    #   run: pnpm --filter web test

    # Lint step disabled - no lint script available
    # - name: Lint
    #   run: pnpm lint
